export const getStores = /* GraphQL */` 
 query getStores($_id: String){
    getStores(_id: $_id){
        _id
        name
        address
        generes
        schedule{
            _id
            name
            start
            end
            days
            abbreviation
            createdAt
            updatedAt
        }
        services{
            _id
            plus
            name
            abbreviation
            type{
                _id
                name
                description
            }
            products{
                productQuantity
            }
            eta
            price
            cost
            serviceFee
            taxes
            description
            discounts
            serviceTime
            sex
            returnTime
            photo{
                filename
                key
            }
            subService{
                _id
                plus
                name
                abbreviation
                eta
                price
                cost
                serviceFee
                taxes
                discounts
                serviceTime
                returnTime
                sex
                createdAt
                updatedAt
            }
            createdAt
            updatedAt
        }
        location{
            lat
            lng
        }
        department
        city
        zone
        phone
        contact
        reservePercentage
    }
}
`;
